In [50]:
import pandas as pd
import numpy as np

from sklearn import preprocessing as pp
from fancyimpute import MICE, SoftImpute, KNN, MatrixFactorization, BiScaler
%pylab inline

df = pd.read_csv('/home/lara/Documents/Repository/Capstone-1_WorldBank_GenderData/finalvars.csv')

# Supervised Learning Modules
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

Populating the interactive namespace from numpy and matplotlib

# Data Wrangling

In [51]:
#count non-NaN rows in each column
df.count()

Unnamed: 0     3945
country        3945
life           3699
bc              639
matdeath       3435
teen           3600
gdp            3644
healthspend    3523
eduspend       2100
dtype: int64

In [52]:
#Drop all rows with NaN values and count how many rows are left
dfdrop = df.dropna()
dfdrop.bc.count()

368

In [29]:
#split data into "Causes" and "Effects" of Contraceptive Use
dfcause = df[['bc', 'gdp', 'healthspend', 'eduspend']]
dfeffect = df[['country', 'bc', 'life', 'matdeath', 'teen']]

#count non-NaN values in "Cause" df
dfcause.dropna().count()

bc             370
gdp            370
healthspend    370
eduspend       370
dtype: int64

In [53]:
#Count non-NaN rows in "Effect" df
dfeffect.dropna().count()

country     624
bc          624
life        624
matdeath    624
teen        624
dtype: int64

In [54]:
#save "Effect" df without NaN rows because there are very few rows with NaNs
effect = dfeffect.dropna()

## Implementing multiple algorithms from the Fancy Impute package to see which works best

In [39]:
#use MICE algorithm in Fancy Impute package to interpolate NaN values in "Causes" df
micefilled = MICE().complete(dfcause)
#turn micefilled nmpy array into pandas df
mice = pd.DataFrame(micefilled, columns= dfcause.columns)

[MICE] Completing matrix with shape (3945, 4)
[MICE] Starting imputation round 1/110, elapsed time 0.001
[MICE] Starting imputation round 2/110, elapsed time 0.014
[MICE] Starting imputation round 3/110, elapsed time 0.022
[MICE] Starting imputation round 4/110, elapsed time 0.028
[MICE] Starting imputation round 5/110, elapsed time 0.034
[MICE] Starting imputation round 6/110, elapsed time 0.040
[MICE] Starting imputation round 7/110, elapsed time 0.047
[MICE] Starting imputation round 8/110, elapsed time 0.053
[MICE] Starting imputation round 9/110, elapsed time 0.059
[MICE] Starting imputation round 10/110, elapsed time 0.065
[MICE] Starting imputation round 11/110, elapsed time 0.098
[MICE] Starting imputation round 12/110, elapsed time 0.106
[MICE] Starting imputation round 13/110, elapsed time 0.125
[MICE] Starting imputation round 14/110, elapsed time 0.152
[MICE] Starting imputation round 15/110, elapsed time 0.163
[MICE] Starting imputation round 16/110, elapsed time 0.175
[MICE] Starting imputation round 17/110, elapsed time 0.276
[MICE] Starting imputation round 18/110, elapsed time 0.283
[MICE] Starting imputation round 19/110, elapsed time 0.299
[MICE] Starting imputation round 20/110, elapsed time 0.306
[MICE] Starting imputation round 21/110, elapsed time 0.316
[MICE] Starting imputation round 22/110, elapsed time 0.331
[MICE] Starting imputation round 23/110, elapsed time 0.368
[MICE] Starting imputation round 24/110, elapsed time 0.380
[MICE] Starting imputation round 25/110, elapsed time 0.394
[MICE] Starting imputation round 26/110, elapsed time 0.397
[MICE] Starting imputation round 27/110, elapsed time 0.420
[MICE] Starting imputation round 28/110, elapsed time 0.431
[MICE] Starting imputation round 29/110, elapsed time 0.435
[MICE] Starting imputation round 30/110, elapsed time 0.438
[MICE] Starting imputation round 31/110, elapsed time 0.443
[MICE] Starting imputation round 32/110, elapsed time 0.467
[MICE] Starting imputation round 33/110, elapsed time 0.475
[MICE] Starting imputation round 34/110, elapsed time 0.481
[MICE] Starting imputation round 35/110, elapsed time 0.501
[MICE] Starting imputation round 36/110, elapsed time 0.505
[MICE] Starting imputation round 37/110, elapsed time 0.518
[MICE] Starting imputation round 38/110, elapsed time 0.523
[MICE] Starting imputation round 39/110, elapsed time 0.529
[MICE] Starting imputation round 40/110, elapsed time 0.534
[MICE] Starting imputation round 41/110, elapsed time 0.539
[MICE] Starting imputation round 42/110, elapsed time 0.545
[MICE] Starting imputation round 43/110, elapsed time 0.549
[MICE] Starting imputation round 44/110, elapsed time 0.553
[MICE] Starting imputation round 45/110, elapsed time 0.557
[MICE] Starting imputation round 46/110, elapsed time 0.561
[MICE] Starting imputation round 47/110, elapsed time 0.565
[MICE] Starting imputation round 48/110, elapsed time 0.569
[MICE] Starting imputation round 49/110, elapsed time 0.573
[MICE] Starting imputation round 50/110, elapsed time 0.578
[MICE] Starting imputation round 51/110, elapsed time 0.582
[MICE] Starting imputation round 52/110, elapsed time 0.586
[MICE] Starting imputation round 53/110, elapsed time 0.591
[MICE] Starting imputation round 54/110, elapsed time 0.596
[MICE] Starting imputation round 55/110, elapsed time 0.601
[MICE] Starting imputation round 56/110, elapsed time 0.606
[MICE] Starting imputation round 57/110, elapsed time 0.610
[MICE] Starting imputation round 58/110, elapsed time 0.614
[MICE] Starting imputation round 59/110, elapsed time 0.618
[MICE] Starting imputation round 60/110, elapsed time 0.629
[MICE] Starting imputation round 61/110, elapsed time 0.632
[MICE] Starting imputation round 62/110, elapsed time 0.636
[MICE] Starting imputation round 63/110, elapsed time 0.639
[MICE] Starting imputation round 64/110, elapsed time 0.650
[MICE] Starting imputation round 65/110, elapsed time 0.676
[MICE] Starting imputation round 66/110, elapsed time 0.687
[MICE] Starting imputation round 67/110, elapsed time 0.704
[MICE] Starting imputation round 68/110, elapsed time 0.707
[MICE] Starting imputation round 69/110, elapsed time 0.714
[MICE] Starting imputation round 70/110, elapsed time 0.718
[MICE] Starting imputation round 71/110, elapsed time 0.722
[MICE] Starting imputation round 72/110, elapsed time 0.726
[MICE] Starting imputation round 73/110, elapsed time 0.730
[MICE] Starting imputation round 74/110, elapsed time 0.774
[MICE] Starting imputation round 75/110, elapsed time 0.779
[MICE] Starting imputation round 76/110, elapsed time 0.782
[MICE] Starting imputation round 77/110, elapsed time 0.785
[MICE] Starting imputation round 78/110, elapsed time 0.788
[MICE] Starting imputation round 79/110, elapsed time 0.792
[MICE] Starting imputation round 80/110, elapsed time 0.796
[MICE] Starting imputation round 81/110, elapsed time 0.800
[MICE] Starting imputation round 82/110, elapsed time 0.804
[MICE] Starting imputation round 83/110, elapsed time 0.808
[MICE] Starting imputation round 84/110, elapsed time 0.812
[MICE] Starting imputation round 85/110, elapsed time 0.815
[MICE] Starting imputation round 86/110, elapsed time 0.818
[MICE] Starting imputation round 87/110, elapsed time 0.821
[MICE] Starting imputation round 88/110, elapsed time 0.824
[MICE] Starting imputation round 89/110, elapsed time 0.827
[MICE] Starting imputation round 90/110, elapsed time 0.837
[MICE] Starting imputation round 91/110, elapsed time 0.850
[MICE] Starting imputation round 92/110, elapsed time 0.853
[MICE] Starting imputation round 93/110, elapsed time 0.857
[MICE] Starting imputation round 94/110, elapsed time 0.881
[MICE] Starting imputation round 95/110, elapsed time 0.892
[MICE] Starting imputation round 96/110, elapsed time 0.901
[MICE] Starting imputation round 97/110, elapsed time 0.913
[MICE] Starting imputation round 98/110, elapsed time 0.917
[MICE] Starting imputation round 99/110, elapsed time 0.920
[MICE] Starting imputation round 100/110, elapsed time 0.922
[MICE] Starting imputation round 101/110, elapsed time 0.925
[MICE] Starting imputation round 102/110, elapsed time 0.928
[MICE] Starting imputation round 103/110, elapsed time 0.931
[MICE] Starting imputation round 104/110, elapsed time 0.934
[MICE] Starting imputation round 105/110, elapsed time 0.937
[MICE] Starting imputation round 106/110, elapsed time 0.941
[MICE] Starting imputation round 107/110, elapsed time 0.945
[MICE] Starting imputation round 108/110, elapsed time 0.949
[MICE] Starting imputation round 109/110, elapsed time 0.953
[MICE] Starting imputation round 110/110, elapsed time 0.957

In [40]:
mice

             bc           gdp  healthspend  eduspend
0      4.900000 -10756.178100     2.551312  4.130685
1     44.072898    119.899037     3.065070  4.442978
2     40.198648    192.153528     0.550723  4.161138
3     10.300000    203.651041     0.607900  4.204472
4     43.313948    224.914712     0.969459  4.133318
5     13.600000    257.175795     0.801919  4.463184
6     18.600000    280.245644     1.062420  4.438390
7     43.618894    380.400955     0.522136  4.454933
8     22.800000    384.131681     1.385584  4.612008
9     40.504821    458.955782     2.586127  4.465732
10    21.800000    569.940729     2.855377  4.511160
11    21.200000    622.379654     2.080093  4.087910
12    43.691072    690.842629     2.920566  3.125620
13    45.037863    653.347488     2.650394  4.544360
14    39.872572    633.947864     2.932834  4.804350
15    57.500000   1175.788981     2.258418  3.286920
16    41.807925   1326.970339     2.292224  3.340600
17    75.100000   1453.642777     2.256326  3.056630
18    45.559973   1890.681557     2.252104  3.064270
19    47.669418   2416.588235     2.679405  3.170080
20    60.100000   2709.142931     2.706455  3.238720
21    48.203831   3005.012903     2.575136  3.157190
22    46.890601   3603.013685     2.629171  3.268680
23    46.220971   4370.539647     2.693898  4.340518
24    69.300000   4114.136545     2.833576  4.308396
25    47.794505   4094.358832     2.476568  4.289356
26    45.753486   4437.811999     2.849171  4.286609
27    43.888114   4247.839852     2.735704  4.618325
28    44.368004   4412.345578     2.835984  3.538000
29    51.963224   4588.649440     2.936373  4.512935
...         ...           ...          ...       ...
3915  41.279827    340.161380     3.719900  1.788190
3916  46.973246    376.981058     3.526559  4.206240
3917  34.200000    376.468040     4.018110  4.466413
3918  44.775409    429.007278     4.187669  4.431940
3919  44.834421    530.553584     3.657084  2.463430
3920  46.588176    691.809459     3.956979  1.735530
3921  42.918523   1030.315360     2.755846  4.788679
3922  40.800000   1103.486577     1.885822  1.240760
3923  44.841454   1365.721205     2.189942  1.099720
3924  43.341884   1134.772998     2.261668  4.659781
3925  46.891621   1456.126526     2.279956  4.363148
3926  48.692236   1635.547304     2.148932  4.466825
3927  47.310285   1724.743564     2.536370  4.099207
3928  43.461804   1839.522481     2.765405  4.722705
3929  49.000000   1725.974549     2.760095  4.392628
3930  43.035650    535.197422     4.367104  4.406524
3931  43.147193    537.717483     3.184205  4.420600
3932  48.304786    499.716415     3.225747  4.535584
3933  44.279752    448.373193     3.224441  4.443677
3934  42.473063    451.171589     3.779543  4.091327
3935  43.966708    443.240136     2.737616  4.135372
3936  60.200000    414.680115     1.058720  4.189354
3937  42.726165    397.956872     0.577384  4.340233
3938  42.700138    327.199084     0.368426  4.151998
3939  64.900000    594.495968     1.483600  4.028499
3940  47.748283    674.268695     1.684360  1.973330
3941  58.500000    768.556409     2.121150  4.588277
3942  44.247798    850.827697     2.771620  4.567534
3943  45.612396    905.500322     2.847450  4.271844
3944  66.900000    931.198185     2.466495  4.009504

[3945 rows x 4 columns]

In [42]:
mice.to_csv('mice.csv')

In [45]:
cause = pd.read_csv('/home/lara/Documents/Repository/Capstone-1_WorldBank_GenderData/mice.csv')

In [46]:
cause.head()

   Unnamed: 0         bc         gdp  healthspend  eduspend
0           0   4.900000  119.000000     2.551312  4.130685
1           1  44.072898  119.899037     3.065070  4.442978
2           2  40.198648  192.153528     0.550723  4.161138
3           3  10.300000  203.651041     0.607900  4.204472
4           4  43.313948  224.914712     0.969459  4.133318

## The MICE algorithm from Fancy Impute is interpolating negative numbers for GDP, so exploring other algorithms for imputing appears to be necessary

In [6]:
#use KNN algorithm in Fancy Impute package to interpolate NaN values in "Causes" df
knnfilled = KNN(k=2).complete(dfcause)
#turn filled nmpy array into pandas df
dfknn = pd.DataFrame(knnfilled, columns= dfcause.columns)

Imputing row 1/3945 with 3 missing, elapsed time: 9.067
Imputing row 101/3945 with 2 missing, elapsed time: 9.076
Imputing row 201/3945 with 1 missing, elapsed time: 9.084
Imputing row 301/3945 with 1 missing, elapsed time: 9.091
Imputing row 401/3945 with 2 missing, elapsed time: 9.100
Imputing row 501/3945 with 1 missing, elapsed time: 9.108
Imputing row 601/3945 with 1 missing, elapsed time: 9.114
Imputing row 701/3945 with 2 missing, elapsed time: 9.122
Imputing row 801/3945 with 4 missing, elapsed time: 9.129
Imputing row 901/3945 with 0 missing, elapsed time: 9.137
Imputing row 1001/3945 with 1 missing, elapsed time: 9.145
Imputing row 1101/3945 with 1 missing, elapsed time: 9.153
Imputing row 1201/3945 with 0 missing, elapsed time: 9.162
Imputing row 1301/3945 with 1 missing, elapsed time: 9.169
Imputing row 1401/3945 with 0 missing, elapsed time: 9.177
Imputing row 1501/3945 with 3 missing, elapsed time: 9.185
Imputing row 1601/3945 with 1 missing, elapsed time: 9.193
Imputing row 1701/3945 with 3 missing, elapsed time: 9.199
Imputing row 1801/3945 with 1 missing, elapsed time: 9.207
Imputing row 1901/3945 with 1 missing, elapsed time: 9.216
Imputing row 2001/3945 with 1 missing, elapsed time: 9.223
Imputing row 2101/3945 with 0 missing, elapsed time: 9.231
Imputing row 2201/3945 with 2 missing, elapsed time: 9.239
Imputing row 2301/3945 with 2 missing, elapsed time: 9.247
Imputing row 2401/3945 with 0 missing, elapsed time: 9.255
Imputing row 2501/3945 with 2 missing, elapsed time: 9.264
Imputing row 2601/3945 with 1 missing, elapsed time: 9.273
Imputing row 2701/3945 with 0 missing, elapsed time: 9.280
Imputing row 2801/3945 with 2 missing, elapsed time: 9.288
Imputing row 2901/3945 with 1 missing, elapsed time: 9.295
Imputing row 3001/3945 with 1 missing, elapsed time: 9.303
Imputing row 3101/3945 with 2 missing, elapsed time: 9.312
Imputing row 3201/3945 with 2 missing, elapsed time: 9.319
Imputing row 3301/3945 with 1 missing, elapsed time: 9.325
Imputing row 3401/3945 with 1 missing, elapsed time: 9.333
Imputing row 3501/3945 with 2 missing, elapsed time: 9.341
Imputing row 3601/3945 with 0 missing, elapsed time: 9.347
Imputing row 3701/3945 with 1 missing, elapsed time: 9.356
Imputing row 3801/3945 with 2 missing, elapsed time: 9.363
Imputing row 3901/3945 with 1 missing, elapsed time: 9.371
[KNN] Warning: 940/15780 still missing after imputation, replacing with 0

In [37]:
dfknn.to_csv('knn.csv')

In [27]:
df

,Unnamed: 0,country,life,bc,matdeath,teen,gdp,healthspend,eduspend
0,0,Afghanistan,55.125878,4.9,1100.0,153.8456,NaN,NaN,NaN
1,1,Afghanistan,55.487537,NaN,1050.0,150.0468,119.899037,NaN,NaN
2,2,Afghanistan,55.857195,NaN,996.0,146.2480,192.153528,0.550723,NaN
3,3,Afghanistan,56.235293,10.3,941.0,140.4764,203.651041,0.607900,NaN
4,4,Afghanistan,56.626317,NaN,881.0,134.7048,224.914712,0.969459,NaN
5,5,Afghanistan,57.027244,13.6,821.0,128.9332,257.175795,0.801919,NaN
6,6,Afghanistan,57.432561,18.6,776.0,123.1616,280.245644,1.062420,NaN
7,7,Afghanistan,57.833829,NaN,724.0,117.3900,380.400955,0.522136,NaN
8,8,Afghanistan,58.225024,22.8,676.0,111.4708,384.131681,1.385584,NaN
9,9,Afghanistan,58.603683,NaN,631.0,105.5516,458.955782,2.586127,NaN
10,10,Afghanistan,58.970829,21.8,584.0,99.6324,569.940729,2.855377,4.51116
11,11,Afghanistan,59.327951,21.2,536.0,93.7132,622.379654,2.080093,4.08791
12,12,Afghanistan,59.679610,NaN,496.0,87.7940,690.842629,2.920566,3.12562
13,13,Afghanistan,60.028268,NaN,459.0,82.2638,653.347488,2.650394,4.54436
14,14,Afghanistan,60.374463,NaN,425.0,76.7336,633.947864,2.932834,4.80435
15,15,Albania,74.271537,57.5,43.0,19.2730,1175.788981,2.258418,3.28692
16,16,Albania,74.732561,NaN,40.0,19.2540,1326.970339,2.292224,3.34060
17,17,Albania,75.154610,75.1,37.0,19.2350,1453.642777,2.256326,3.05663
18,18,Albania,75.523293,NaN,35.0,19.1080,1890.681557,2.252104,3.06427
19,19,Albania,75.831220,NaN,31.0,18.9810,2416.588235,2.679405,3.17008
20,20,Albania,76.081610,60.1,30.0,18.8540,2709.142931,2.706455,3.23872
21,21,Albania,76.286122,NaN,29.0,18.7270,3005.012903,2.575136,3.15719
22,22,Albania,76.470293,NaN,30.0,18.6000,3603.013685,2.629171,3.26868
23,23,Albania,76.652073,NaN,30.0,19.0396,4370.539647,2.693898,NaN
24,24,Albania,76.840366,69.3,30.0,19.4792,4114.136545,2.833576,NaN
25,25,Albania,77.036951,NaN,30.0,19.9188,4094.358832,2.476568,NaN
26,26,Albania,77.240585,NaN,30.0,20.3584,4437.811999,2.849171,NaN
27,27,Albania,77.443976,NaN,30.0,20.7980,4247.839852,2.735704,NaN
28,28,Albania,77.640463,NaN,29.0,21.1438,4412.345578,2.835984,3.53800
29,29,Albania,77.830463,NaN,29.0,21.4896,4588.649440,2.936373,NaN
...,...,...,...,...,...,...,...,...,...
3915,3915,Zambia,43.456683,NaN,541.0,143.4404,340.161380,3.719900,1.78819
3916,3916,Zambia,44.272488,NaN,518.0,143.3582,376.981058,3.526559,NaN
3917,3917,Zambia,45.306659,34.2,493.0,143.2760,376.468040,4.018110,NaN
3918,3918,Zambia,46.538634,NaN,472.0,139.0234,429.007278,4.187669,NaN
3919,3919,Zambia,47.932390,NaN,414.0,134.7708,530.553584,3.657084,2.46343
3920,3920,Zambia,49.429390,NaN,372.0,130.5182,691.809459,3.956979,1.73553
3921,3921,Zambia,50.966610,NaN,338.0,126.2656,1030.315360,2.755846,NaN
3922,3922,Zambia,52.477146,40.8,311.0,122.0130,1103.486577,1.885822,1.24076
3923,3923,Zambia,53.905634,NaN,289.0,118.2768,1365.721205,2.189942,1.09972
3924,3924,Zambia,55.214171,NaN,274.0,114.5406,1134.772998,2.261668,NaN
3925,3925,Zambia,56.383854,NaN,262.0,110.8044,1456.126526,2.279956,NaN
3926,3926,Zambia,57.422195,NaN,251.0,107.0682,1635.547304,2.148932,NaN
3927,3927,Zambia,58.363317,NaN,243.0,103.3320,1724.743564,2.536370,NaN
3928,3928,Zambia,59.237366,NaN,237.0,98.1738,1839.522481,2.765405,NaN
3929,3929,Zambia,60.047049,49.0,231.0,93.0156,1725.974549,2.760095,NaN
3930,3930,Zimbabwe,41.689439,NaN,590.0,108.4110,535.197422,4.367104,NaN
3931,3931,Zimbabwe,40.996805,NaN,621.0,107.8400,537.717483,3.184205,NaN
3932,3932,Zimbabwe,40.679146,NaN,642.0,107.2690,499.716415,3.225747,NaN
3933,3933,Zimbabwe,40.702488,NaN,657.0,109.3162,448.373193,3.224441,NaN
3934,3934,Zimbabwe,41.059341,NaN,648.0,111.3634,451.171589,3.779543,NaN
3935,3935,Zimbabwe,41.759610,NaN,629.0,113.4106,443.240136,2.737616,NaN
3936,3936,Zimbabwe,42.810707,60.2,600.0,115.4578,414.680115,1.058720,NaN
3937,3937,Zimbabwe,44.177756,NaN,564.0,117.5050,397.956872,0.577384,NaN
3938,3938,Zimbabwe,45.804488,NaN,533.0,116.6702,327.199084,0.368426,NaN
3939,3939,Zimbabwe,47.624659,64.9,485.0,115.8354,594.495968,1.483600,NaN
3940,3940,Zimbabwe,49.574659,NaN,446.0,115.0006,674.268695,1.684360,1.97333
3941,3941,Zimbabwe,51.600366,58.5,409.0,114.1658,768.556409,2.121150,NaN
3942,3942,Zimbabwe,53.643073,NaN,379.0,113.3310,850.827697,2.771620,NaN
3943,3943,Zimbabwe,55.633000,NaN,369.0,111.8664,905.500322,2.847450,NaN
3944,3944,Zimbabwe,57.498317,66.9,401.0,110.4018,931.198185,2.466495,NaN

### KNN seems to have interpolated an excessively high number for GDP in the

In [22]:
#use SoftImpute algorithm in Fancy Impute package to interpolate NaN values in "Causes" df
softfilled = SoftImpute().complete(dfcause)
#turn filled nmpy array into pandas df
softdf = pd.DataFrame(softfilled, columns= dfcause.columns)

[SoftImpute] Max Singular Value of X_init = 1373789.282534
[SoftImpute] Iter 1: observed MAE=93.283127 rank=1
[SoftImpute] Iter 2: observed MAE=93.154539 rank=1
[SoftImpute] Iter 3: observed MAE=93.094391 rank=1
[SoftImpute] Iter 4: observed MAE=93.054360 rank=1
[SoftImpute] Iter 5: observed MAE=93.022870 rank=1
[SoftImpute] Iter 6: observed MAE=92.994990 rank=1
[SoftImpute] Iter 7: observed MAE=92.969587 rank=1
[SoftImpute] Iter 8: observed MAE=92.945994 rank=1
[SoftImpute] Iter 9: observed MAE=92.923982 rank=1
[SoftImpute] Iter 10: observed MAE=92.903403 rank=1
[SoftImpute] Iter 11: observed MAE=92.884149 rank=1
[SoftImpute] Iter 12: observed MAE=92.866125 rank=1
[SoftImpute] Iter 13: observed MAE=92.849251 rank=1
[SoftImpute] Iter 14: observed MAE=92.833558 rank=1
[SoftImpute] Iter 15: observed MAE=92.818977 rank=1
[SoftImpute] Iter 16: observed MAE=92.805323 rank=1
[SoftImpute] Iter 17: observed MAE=92.792563 rank=1
[SoftImpute] Iter 18: observed MAE=92.781024 rank=1
[SoftImpute] Iter 19: observed MAE=92.770338 rank=1
[SoftImpute] Iter 20: observed MAE=92.760558 rank=1
[SoftImpute] Iter 21: observed MAE=92.751761 rank=1
[SoftImpute] Iter 22: observed MAE=92.743576 rank=1
[SoftImpute] Iter 23: observed MAE=92.735911 rank=1
[SoftImpute] Iter 24: observed MAE=92.728770 rank=1
[SoftImpute] Iter 25: observed MAE=92.722224 rank=1
[SoftImpute] Iter 26: observed MAE=92.716260 rank=1
[SoftImpute] Iter 27: observed MAE=92.710910 rank=1
[SoftImpute] Iter 28: observed MAE=92.706136 rank=1
[SoftImpute] Iter 29: observed MAE=92.701796 rank=1
[SoftImpute] Iter 30: observed MAE=92.697792 rank=1
[SoftImpute] Iter 31: observed MAE=92.694049 rank=1
[SoftImpute] Iter 32: observed MAE=92.690591 rank=1
[SoftImpute] Iter 33: observed MAE=92.687606 rank=1
[SoftImpute] Iter 34: observed MAE=92.684907 rank=1
[SoftImpute] Iter 35: observed MAE=92.682379 rank=1
[SoftImpute] Iter 36: observed MAE=92.680012 rank=1
[SoftImpute] Iter 37: observed MAE=92.677796 rank=1
[SoftImpute] Iter 38: observed MAE=92.675721 rank=1
[SoftImpute] Iter 39: observed MAE=92.673778 rank=1
[SoftImpute] Iter 40: observed MAE=92.671959 rank=1
[SoftImpute] Iter 41: observed MAE=92.670257 rank=1
[SoftImpute] Iter 42: observed MAE=92.668733 rank=1
[SoftImpute] Iter 43: observed MAE=92.667305 rank=1
[SoftImpute] Iter 44: observed MAE=92.665969 rank=1
[SoftImpute] Iter 45: observed MAE=92.664717 rank=1
[SoftImpute] Iter 46: observed MAE=92.663545 rank=1
[SoftImpute] Iter 47: observed MAE=92.662448 rank=1
[SoftImpute] Iter 48: observed MAE=92.661420 rank=1
[SoftImpute] Iter 49: observed MAE=92.660458 rank=1
[SoftImpute] Iter 50: observed MAE=92.659581 rank=1
[SoftImpute] Iter 51: observed MAE=92.658780 rank=1
[SoftImpute] Iter 52: observed MAE=92.658029 rank=1
[SoftImpute] Iter 53: observed MAE=92.657326 rank=1
[SoftImpute] Iter 54: observed MAE=92.656667 rank=1
[SoftImpute] Iter 55: observed MAE=92.656051 rank=1
[SoftImpute] Iter 56: observed MAE=92.655474 rank=1
[SoftImpute] Iter 57: observed MAE=92.654933 rank=1
[SoftImpute] Iter 58: observed MAE=92.654427 rank=1
[SoftImpute] Iter 59: observed MAE=92.653953 rank=1
[SoftImpute] Iter 60: observed MAE=92.653509 rank=1
[SoftImpute] Iter 61: observed MAE=92.653094 rank=1
[SoftImpute] Iter 62: observed MAE=92.652705 rank=1
[SoftImpute] Iter 63: observed MAE=92.652340 rank=1
[SoftImpute] Iter 64: observed MAE=92.651999 rank=1
[SoftImpute] Iter 65: observed MAE=92.651679 rank=1
[SoftImpute] Stopped after iteration 65 for lambda=27475.785651

In [24]:
softdf

             bc          gdp  healthspend  eduspend
0      4.900000     0.274759     0.000037  0.000032
1      0.213342   119.899037     0.016004  0.013659
2      0.341907   192.153528     0.550723  0.021890
3     10.300000   203.651041     0.607900  0.023202
4      0.400201   224.914712     0.969459  0.025622
5     13.600000   257.175795     0.801919  0.029300
6     18.600000   280.245644     1.062420  0.031929
7      0.676864   380.400955     0.522136  0.043334
8     22.800000   384.131681     1.385584  0.043764
9      0.816640   458.955782     2.586127  0.052283
10    21.800000   569.940729     2.855377  4.511160
11    21.200000   622.379654     2.080093  4.087910
12     1.229247   690.842629     2.920566  3.125620
13     1.162531   653.347488     2.650394  4.544360
14     1.128012   633.947864     2.932834  4.804350
15    57.500000  1175.788981     2.258418  3.286920
16     2.361136  1326.970339     2.292224  3.340600
17    75.100000  1453.642777     2.256326  3.056630
18     3.364172  1890.681557     2.252104  3.064270
19     4.299940  2416.588235     2.679405  3.170080
20    60.100000  2709.142931     2.706455  3.238720
21     5.346950  3005.012903     2.575136  3.157190
22     6.410998  3603.013685     2.629171  3.268680
23     7.776689  4370.539647     2.693898  0.497882
24    69.300000  4114.136545     2.833576  0.468686
25     7.285269  4094.358832     2.476568  0.466420
26     7.896390  4437.811999     2.849171  0.505546
27     7.558364  4247.839852     2.735704  0.483905
28     7.851077  4412.345578     2.835984  3.538000
29     8.164782  4588.649440     2.936373  0.522729
...         ...          ...          ...       ...
3915   0.605265   340.161380     3.719900  1.788190
3916   0.670779   376.981058     3.526559  0.042945
3917  34.200000   376.468040     4.018110  0.042893
3918   0.763352   429.007278     4.187669  0.048872
3919   0.944038   530.553584     3.657084  2.463430
3920   1.230968   691.809459     3.956979  1.735530
3921   1.833285  1030.315360     2.755846  0.117371
3922  40.800000  1103.486577     1.885822  1.240760
3923   2.430087  1365.721205     2.189942  1.099720
3924   2.019151  1134.772998     2.261668  0.129271
3925   2.590949  1456.126526     2.279956  0.165879
3926   2.910200  1635.547304     2.148932  0.186318
3927   3.068911  1724.743564     2.536370  0.196479
3928   3.273142  1839.522481     2.765405  0.209554
3929  49.000000  1725.974549     2.760095  0.196629
3930   0.952301   535.197422     4.367104  0.060969
3931   0.956785   537.717483     3.184205  0.061256
3932   0.889168   499.716415     3.225747  0.056927
3933   0.797810   448.373193     3.224441  0.051078
3934   0.802790   451.171589     3.779543  0.051397
3935   0.788677   443.240136     2.737616  0.050493
3936  60.200000   414.680115     1.058720  0.047252
3937   0.708102   397.956872     0.577384  0.045334
3938   0.582199   327.199084     0.368426  0.037274
3939  64.900000   594.495968     1.483600  0.067737
3940   1.199756   674.268695     1.684360  1.973330
3941  58.500000   768.556409     2.121150  0.087564
3942   1.513915   850.827697     2.771620  0.096924
3943   1.611196   905.500322     2.847450  0.103153
3944  66.900000   931.198185     2.466495  0.106094

[3945 rows x 4 columns]

### Soft Impute seems to be interpolating excessively small numbers for all values

In [14]:
#use MatrixFactorization algorithm in Fancy Impute package to interpolate NaN values in "Causes" df
mffilled = MatrixFactorization().complete(dfcause)
#turn filled nmpy array into pandas df
mfdf = pd.DataFrame(mffilled, columns= dfcause.columns)

train: 1 of 1 mini-batches from (3945, 4)
downhill: compiling evaluation function
downhill: compiling Adam optimizer
downhill: setting: rms_halflife = 14
downhill: setting: rms_regularizer = 1e-08
downhill: setting: patience = 5
downhill: setting: validate_every = 10
downhill: setting: min_improvement = 0.005
downhill: setting: max_gradient_norm = 5
downhill: setting: max_gradient_elem = 0
downhill: setting: learning_rate = TensorConstant{0.001}
downhill: setting: momentum = 0
downhill: setting: nesterov = False
downhill: validation 0 loss=119600978.912601 error=119600978.831751 grad(U)=145681.469725 grad(V)=350017.812784 *
downhill: Adam 1 loss=119600978.912601 error=119600978.831751 grad(U)=145681.469725 grad(V)=350017.812784
downhill: Adam 2 loss=119600942.509747 error=119600942.428949 grad(U)=145673.538692 grad(V)=346319.107871
downhill: Adam 3 loss=119600893.332482 error=119600893.251755 grad(U)=145664.698765 grad(V)=342303.074931
downhill: Adam 4 loss=119600835.751961 error=119600835.671318 grad(U)=145658.791991 grad(V)=339037.891416
downhill: Adam 5 loss=119600772.135058 error=119600772.054506 grad(U)=145661.784706 grad(V)=337237.890372
downhill: Adam 6 loss=119600704.019560 error=119600703.939105 grad(U)=145683.851015 grad(V)=337419.235191
downhill: Adam 7 loss=119600632.487712 error=119600632.407357 grad(U)=145739.068879 grad(V)=339960.576215
downhill: Adam 8 loss=119600558.334551 error=119600558.254298 grad(U)=145838.126080 grad(V)=345136.934131
downhill: Adam 9 loss=119600482.166820 error=119600482.086669 grad(U)=145980.958719 grad(V)=353142.194703
downhill: Adam 10 loss=119600404.463608 error=119600404.383560 grad(U)=146160.769661 grad(V)=364105.338815
downhill: validation 1 loss=119600325.609656 error=119600325.529709 grad(U)=146370.710204 grad(V)=378102.823484
downhill: Adam 11 loss=119600325.609656 error=119600325.529709 grad(U)=146370.710204 grad(V)=378102.823484
downhill: Adam 12 loss=119600245.915677 error=119600245.835832 grad(U)=146606.003130 grad(V)=395168.368615
downhill: Adam 13 loss=119600165.633088 error=119600165.553343 grad(U)=146863.669355 grad(V)=415300.883886
downhill: Adam 14 loss=119600084.965313 error=119600084.885667 grad(U)=147141.902203 grad(V)=438471.063873
downhill: Adam 15 loss=119600004.076600 error=119600003.997051 grad(U)=147439.597235 grad(V)=464627.054130
downhill: Adam 16 loss=119599923.099017 error=119599923.019563 grad(U)=147756.052195 grad(V)=493699.485348
downhill: Adam 17 loss=119599842.138095 error=119599842.058735 grad(U)=148090.780373 grad(V)=525606.082142
downhill: Adam 18 loss=119599761.277495 error=119599761.198227 grad(U)=148443.392170 grad(V)=560255.963407
downhill: Adam 19 loss=119599680.582897 error=119599680.503719 grad(U)=148813.519821 grad(V)=597553.655549
downhill: Adam 20 loss=119599600.105308 error=119599600.026218 grad(U)=149200.770412 grad(V)=637402.748582
downhill: validation 2 loss=119599519.883855 error=119599519.804849 grad(U)=149604.698596 grad(V)=679709.060342
downhill: Adam 21 loss=119599519.883855 error=119599519.804849 grad(U)=149604.698596 grad(V)=679709.060342
downhill: Adam 22 loss=119599439.948137 error=119599439.869214 grad(U)=150024.794572 grad(V)=724383.155866
downhill: Adam 23 loss=119599360.320185 error=119599360.241341 grad(U)=150460.482347 grad(V)=771342.105092
downhill: Adam 24 loss=119599281.016038 error=119599280.937272 grad(U)=150911.126873 grad(V)=820510.441371
downhill: Adam 25 loss=119599202.047012 error=119599201.968320 grad(U)=151376.045056 grad(V)=871820.379239
downhill: Adam 26 loss=119599123.420672 error=119599123.342052 grad(U)=151854.520470 grad(V)=925211.432517
downhill: Adam 27 loss=119599045.141574 error=119599045.063023 grad(U)=152345.817616 grad(V)=980629.620929
downhill: Adam 28 loss=119598967.211823 error=119598967.133338 grad(U)=152849.195057 grad(V)=1038026.459292
downhill: Adam 29 loss=119598889.631492 error=119598889.553070 grad(U)=153363.918037 grad(V)=1097357.895854
downhill: Adam 30 loss=119598812.398939 error=119598812.320578 grad(U)=153889.266505 grad(V)=1158583.320560
downhill: validation 3 loss=119598735.511059 error=119598735.432756 grad(U)=154424.542928 grad(V)=1221664.715360
downhill: Adam 31 loss=119598735.511059 error=119598735.432756 grad(U)=154424.542928 grad(V)=1221664.715360
downhill: Adam 32 loss=119598658.963484 error=119598658.885237 grad(U)=154969.076614 grad(V)=1286565.976863
downhill: Adam 33 loss=119598582.750756 error=119598582.672561 grad(U)=155522.227434 grad(V)=1353252.411465
downhill: Adam 34 loss=119598506.866477 error=119598506.788333 grad(U)=156083.386563 grad(V)=1421690.384826
downhill: Adam 35 loss=119598431.303450 error=119598431.225354 grad(U)=156651.977780 grad(V)=1491847.098748
downhill: Adam 36 loss=119598356.053803 error=119598355.975753 grad(U)=157227.456920 grad(V)=1563690.466496
downhill: Adam 37 loss=119598281.109107 error=119598281.031100 grad(U)=157809.311476 grad(V)=1637189.059479
downhill: Adam 38 loss=119598206.460487 error=119598206.382522 grad(U)=158397.058879 grad(V)=1712312.102201
downhill: Adam 39 loss=119598132.098723 error=119598132.020796 grad(U)=158990.245662 grad(V)=1789029.496808
downhill: Adam 40 loss=119598058.014341 error=119598057.936451 grad(U)=159588.445987 grad(V)=1867311.863143
downhill: validation 4 loss=119597984.197702 error=119597984.119847 grad(U)=160191.260296 grad(V)=1947130.583934
downhill: Adam 41 loss=119597984.197702 error=119597984.119847 grad(U)=160191.260296 grad(V)=1947130.583934
downhill: Adam 42 loss=119597910.639077 error=119597910.561255 grad(U)=160798.313410 grad(V)=2028457.848126
downhill: Adam 43 loss=119597837.328713 error=119597837.250922 grad(U)=161409.253717 grad(V)=2111266.687776
downhill: Adam 44 loss=119597764.256896 error=119597764.179134 grad(U)=162023.751554 grad(V)=2195531.005993
downhill: Adam 45 loss=119597691.414000 error=119597691.336266 grad(U)=162641.497912 grad(V)=2281225.594773
downhill: Adam 46 loss=119597618.790535 error=119597618.712827 grad(U)=163262.203334 grad(V)=2368326.142655
downhill: Adam 47 loss=119597546.377180 error=119597546.299496 grad(U)=163885.596948 grad(V)=2456809.232767
downhill: Adam 48 loss=119597474.164814 error=119597474.087154 grad(U)=164511.424868 grad(V)=2546652.332296
downhill: Adam 49 loss=119597402.144543 error=119597402.066904 grad(U)=165139.449786 grad(V)=2637833.774593
downhill: Adam 50 loss=119597330.307714 error=119597330.230095 grad(U)=165769.449851 grad(V)=2730332.735339
downhill: validation 5 loss=119597258.645933 error=119597258.568333 grad(U)=166401.217598 grad(V)=2824129.204028
downhill: Adam 51 loss=119597258.645933 error=119597258.568333 grad(U)=166401.217598 grad(V)=2824129.204028
downhill: Adam 52 loss=119597187.151071 error=119597187.073489 grad(U)=167034.559243 grad(V)=2919203.952025
downhill: Adam 53 loss=119597115.815273 error=119597115.737706 grad(U)=167669.293962 grad(V)=3015538.498399
downhill: Adam 54 loss=119597044.630954 error=119597044.553402 grad(U)=168305.253145 grad(V)=3113115.074419
downhill: Adam 55 loss=119596973.590806 error=119596973.513269 grad(U)=168942.279630 grad(V)=3211916.587658
downhill: Adam 56 loss=119596902.687793 error=119596902.610268 grad(U)=169580.227255 grad(V)=3311926.586303
downhill: Adam 57 loss=119596831.915144 error=119596831.837631 grad(U)=170218.959725 grad(V)=3413129.224232
downhill: Adam 58 loss=119596761.266349 error=119596761.188847 grad(U)=170858.350750 grad(V)=3515509.227292
downhill: Adam 59 loss=119596690.735155 error=119596690.657662 grad(U)=171498.282741 grad(V)=3619051.861079
downhill: Adam 60 loss=119596620.315551 error=119596620.238067 grad(U)=172138.646997 grad(V)=3723742.900379
downhill: validation 6 loss=119596550.001766 error=119596549.924290 grad(U)=172779.342509 grad(V)=3829568.600418
downhill: patience elapsed!

In [15]:
mfdf.head()

          bc         gdp  healthspend  eduspend
0   4.900000    1.483410     0.260645 -0.912306
1  -2.142803  119.899037    -4.608279 -1.949659
2   0.925320  192.153528     0.550723  0.696550
3  10.300000  203.651041     0.607900  0.571148
4  -0.453075  224.914712     0.969459  1.825503

Matrix Factorization resulted in negative numbers for Health and Education Spending, which do not make sense.

In [56]:
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('DT', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('RF', RandomForestClassifier(n_jobs = -1, n_estimators = 500)))

In [57]:
Y = df.bc
X = pd.concat(
    [cause[['gdp', 'healthspend', 'eduspend']]],
    axis = 1)

In [58]:
#a function to evaluate each model
def run_models(train_data):
    results = []
    names = []

    for name, model in models:
        kfold = model_selection.KFold(n_splits=10, random_state=11)
        cv_results = model_selection.cross_val_score(model, train_data, Y, cv=kfold, scoring='accuracy')
        results.append(cv_results)
        names.append(name)
        msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
        print(msg)
'''
    # boxplot algorithm comparison
    fig = pyplot.figure()
    fig.suptitle(title)
    ax = fig.add_subplot(111)
    pyplot.boxplot(results)
    ax.set_xticklabels(names)
    pyplot.ylim(0,1)
    pyplot.show()
    '''

'\n    # boxplot algorithm comparison\n    fig = pyplot.figure()\n    fig.suptitle(title)\n    ax = fig.add_subplot(111)\n    pyplot.boxplot(results)\n    ax.set_xticklabels(names)\n    pyplot.ylim(0,1)\n    pyplot.show()\n    '

In [59]:
run_models(X)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').